const male={
    head:{
        pivotX:64,
        pivotY:128,
        offsetRotation:-Math.PI/2,
        rotationLimit:[-Math.PI/8,Math.PI/8],
    },
    leftArm:{
        pivotX:45,
        pivotY:24,
        length:47.72,
        offsetRotation:Math.PI/180*125,
    },
    leftHand:{
        pivotX:20,
        pivotY:11,
        length:108.93,
        offsetRotation:Math.PI/2,
    },
    rightArm:{
        pivotX:75-45,
        pivotY:24,
        length:50.43,
        offsetRotation:Math.PI/180*55,
    },
    rightHand:{
        pivotX:20,
        pivotY:11,
        length:108.98,
        offsetRotation:Math.PI/2,
    },
    leftLeg:{
        pivotX:26,
        pivotY:20,
        length:62,
        offsetRotation:Math.PI/2,
    },
    leftFoot:{
        pivotX:55,
        pivotY:15,
        length:90,
        offsetRotation:Math.PI/2,
    },
    rightLeg:{
        pivotX:56-26,
        pivotY:20,
        length:62,
        offsetRotation:Math.PI/2,
    },
    rightFoot:{
        pivotX:74-55,
        pivotY:15,
        length:90,
        offsetRotation:Math.PI/2,
    },
};
const female = {
    head:{
        pivotX:55,
        pivotY:115,
        offsetRotation:-Math.PI/2,
        rotationLimit:[-Math.PI/8,Math.PI/8],
    },
    leftArm:{
        pivotX:16,
        pivotY:10,
        length:51.96,
        offsetRotation:Math.PI/180*90,
    },
    leftHand:{
        pivotX:23,
        pivotY:12,
        length:108.13,
        offsetRotation:Math.PI/180*90,
    },
    rightArm:{
        pivotX:17,
        pivotY:10,
        length:50.94,
        offsetRotation:Math.PI/180*90,
    },
    rightHand:{
        pivotX:16,
        pivotY:17,
        length:103.3,
        offsetRotation:Math.PI/180*90,
    },
    leftLeg:{
        pivotX:25,
        pivotY:15,
        length:80.62,
        offsetRotation:Math.PI/180*90,
        rotationLimit:[-Math.PI/3.5,Math.PI/7],
    },
    leftFoot:{
        pivotX:32,
        pivotY:12,
        length:88.3,
        offsetRotation:Math.PI/180*90,
    },
    rightLeg:{
        pivotX:25,
        pivotY:15,
        length:80.62,
        offsetRotation:Math.PI/180*90,
        rotationLimit:[-Math.PI/7,Math.PI/3.5],
    },
    rightFoot:{
        pivotX:50-32,
        pivotY:12,
        length:88.3,
        offsetRotation:Math.PI/180*90,
    },
};
export default {
    male:{
        bones:[
            {
                child:'leftLeg',x:37,y:188,
                bones:[{child:'leftFoot',x:26,y:82,}]
            },
            {
                child:'rightLeg',x:124-33,y:188,
                bones:[{child:'rightFoot',x:50-26,y:82,}]
            },
            {
                child:'leftArm',x:16,y:47,
                bones:[{child:'leftHand',x:15,y:66,}]
            },
            {
                child:'rightArm',x:124-16,y:47,
                bones:[{child:'rightHand',x:60,y:66,}]
            },
            {child:'head',x:63,y:12},
        ],
        children:{
            head:male.head,
            leftArm:male.leftArm,
            leftHand:male.leftHand,
            rightArm:male.rightArm,
            rightHand:male.rightHand,
            leftLeg:male.leftLeg,
            leftFoot:male.leftFoot,
            rightLeg:male.rightLeg,
            rightFoot:male.rightFoot,
        }
    },
    female:{
        bones:[
            {
                child:'leftLeg',x:50,y:180,
                bones:[{child:'leftFoot',x:35,y:95,}]
            },
            {
                child:'rightLeg',x:137-50,y:180,
                bones:[{child:'rightFoot',x:56-35,y:95,}]
            },
            {
                child:'leftArm',x:22,y:47,
                bones:[{child:'leftHand',x:17,y:61,}]
            },
            {
                child:'rightArm',x:137-18,y:47,
                bones:[{child:'rightHand',x:17,y:61,}]
            },
            {child:'head',x:70,y:8},
        ],
        children:{
            head:female.head,
            leftArm:female.leftArm,
            leftHand:female.leftHand,
            rightArm:female.rightArm,
            rightHand:female.rightHand,
            leftLeg:female.leftLeg,
            leftFoot:female.leftFoot,
            rightLeg:female.rightLeg,
            rightFoot:female.rightFoot,
        }
    }
};